CC = gcc
LIB = -lsocket -lnsl myftp.o -lpthread

all: myftp myftpclient myftpserver

myftp: myftp.c
	${CC} -c myftp.c

myftpserver: myftp.c myftpserver.c
	${CC} -o myftpserver myftpserver.c ${LIB}

myftpclient: myftp.c myftpclient.c
	${CC} -o myftpclient  myftpclient.c ${LIB}

clean:
	rm myftpserver
	rm myftpclient
